### ISSUE TITLE
Error in CFSAN call_consensus: ValueError exception in function __iter__ at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py

### ISSUE THREAD

**Issue by DagmaraNiedziela** [CFSAN-Biostatistics/snp-pipeline#21]
I am running CFSAN SNP pipeline installed with staphb-tk using the following command: 
staphb-tk cfsan-snp run -s ./scratch/Mbandaka_new/new_externals_fastq  -o ./scratch/Mbandaka_new/CFSAN_results ./scratch/Mbandaka_new/all_genomes/Mbandaka_ATCC_51958.fasta 

I tested the Lambda virus files and it worked fine start to finish. Now I am running 300 bacterial genomes through the pipeline. 

I am receiving the following error: 

Error detected while running cfsan_snp_pipeline call_consensus.

The command line was:
    cfsan_snp_pipeline call_consensus -l /mount1//CFSAN_results/snplist.txt -o /mount1//new_externals_fastq/1492696/consensus.fasta --vcfRefName Mbandaka_ATCC_51958.fasta --verbose 1 --minConsFreq 0.6 --minConsDpth 3 --vcfFileName consensus.vcf --vcfFileName consensus.vcf /mount1//new_externals_fastq/1492696/reads.all.pileup

ValueError exception in function __iter__ at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py
    chrom, pos = split_line[:2]

Could you please let me know what I can do?

**Comment by hughrandFDA** [comment]
Hi Dagmara,

Apologies for the slow reply. The person that supports this code moved on to another position last month and we don’t have someone to cover for this yet. I will try and see if one of the people here that uses the pipeline a lot has any ideas.

Hugh

From: DagmaraNiedziela ***@***.***>
Sent: Friday, May 21, 2021 8:43 AM
To: CFSAN-Biostatistics/snp-pipeline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [CFSAN-Biostatistics/snp-pipeline] Error in CFSAN call_consensus: ValueError exception in function __iter__ at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py (#21)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


I am running CFSAN SNP pipeline installed with staphb-tk using the following command:
staphb-tk cfsan-snp run -s ./scratch/Mbandaka_new/new_externals_fastq -o ./scratch/Mbandaka_new/CFSAN_results ./scratch/Mbandaka_new/all_genomes/Mbandaka_ATCC_51958.fasta

I tested the Lambda virus files and it worked fine start to finish. Now I am running 300 bacterial genomes through the pipeline.

I am receiving the following error:

Error detected while running cfsan_snp_pipeline call_consensus.

The command line was:
cfsan_snp_pipeline call_consensus -l /mount1//CFSAN_results/snplist.txt -o /mount1//new_externals_fastq/1492696/consensus.fasta --vcfRefName Mbandaka_ATCC_51958.fasta --verbose 1 --minConsFreq 0.6 --minConsDpth 3 --vcfFileName consensus.vcf --vcfFileName consensus.vcf /mount1//new_externals_fastq/1492696/reads.all.pileup

ValueError exception in function iter at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py
chrom, pos = split_line[:2]

Could you please let me know what I can do?

**Comment by DagmaraNiedziela** [comment]
Thank you Hugh!

**Comment by hughrandFDA** [comment]
Hi Dagmara,

Current thought is that something is wrong with the pileup file. Can you first check just to be sure that the file is not empty?
Some other things:

  1.  Can you share your data so we can try to reproduce here?
  2.  It looks like you are running under Python 2.7. I think the staphb-tk is built under a 3.x version of Python. The SNP Pipeline does work under the older versions of Python, but not sure what happens if you install it with staphb-tk (as opposed to installing it directly with the directions from readthedocs.com).
Hugh

From: DagmaraNiedziela ***@***.***>
Sent: Saturday, May 29, 2021 8:10 AM
To: CFSAN-Biostatistics/snp-pipeline ***@***.***>
Cc: Rand, Hugh ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [CFSAN-Biostatistics/snp-pipeline] Error in CFSAN call_consensus: ValueError exception in function __iter__ at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py (#21)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Thank you Hugh!

**Comment by DagmaraNiedziela** [comment]
Hi Hugh, 

Thank you for the tips. I asked my PI about sharing the data (whether I can and how) and I will get back to you on that. 

I tried to look at the pileup file, but it does not exist, and neither does the python 2.7 folder... I think this has something to do with the containerised way staphb runs things - in their presentation it states that docker images of software are deleted after use, which is probably why I cannot look at the pileup file. However, again, the test round runs fine, with no errors, in Python 2.7. 

I have staphb installed under python 3.6, and my system version of python is 3.6.5. 

When I run the lambda virus test, all commands run under Python2.7. For example, for call_consensus, this is the sample output: 
# Command           : /usr/local/bin/cfsan_snp_pipeline call_consensus -f -l ./snplist_preserved.txt -o snp_test/testLambdaVirus/samples/sample3/consensus_preserved.fasta -e snp_test/testLambdaVirus/samples/sample3/var.flt_removed.vcf --vcfRefName lambda_virus.fasta --verbose 1 --minConsFreq 0.6 --minConsDpth 3 --vcfFileName consensus.vcf --vcfFileName consensus_preserved.vcf snp_test/testLambdaVirus/samples/sample3/reads.all.pileup
# Working Directory : /data
# Hostname          : login
# RAM               : 257243 MB
# Python Version    : 2.7.12 (default, Nov 12 2018, 14:36:49)  [GCC 5.4.0 20160609]
# Program Version   : cfsan_snp_pipeline call_consensus 2.1.0

On the note of CFSAN installation, I had it installed directly also, but the pipeline was not working due to dependencies - which is why I am using staphb. 
I decided to run the whole pipeline again from scratch and see what happens (it was ran about 6 times with various errors popping up, so maybe some files got corrupted along the way). I will send a message if that solves the problem. I will also look into how I can force the pipeline to run with python 3. 

Dagmara

**Comment by hughrandFDA** [comment]
Hmm… I am going to pass this on to one of our folk here that is going to be doing some support work for this code. We will see what he thinks. This code has been hammered enough that I suspect it has something to do with the setup/configuration it is running in.

Hugh

From: DagmaraNiedziela ***@***.***>
Sent: Friday, June 4, 2021 6:55 AM
To: CFSAN-Biostatistics/snp-pipeline ***@***.***>
Cc: Rand, Hugh ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [CFSAN-Biostatistics/snp-pipeline] Error in CFSAN call_consensus: ValueError exception in function __iter__ at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py (#21)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi Hugh,

Thank you for the tips. I asked my PI about sharing the data (whether I can and how) and I will get back to you on that.

I tried to look at the pileup file, but it does not exist, and neither does the python 2.7 folder... I think this has something to do with the containerised way staphb runs things - in their presentation it states that docker images of software are deleted after use, which is probably why I cannot look at the pileup file. However, again, the test round runs fine, with no errors, in Python 2.7.

I have staphb installed under python 3.6, and my system version of python is 3.6.5.

When I run the lambda virus test, all commands run under Python2.7. For example, for call_consensus, this is the sample output:

Command : /usr/local/bin/cfsan_snp_pipeline call_consensus -f -l ./snplist_preserved.txt -o snp_test/testLambdaVirus/samples/sample3/consensus_preserved.fasta -e snp_test/testLambdaVirus/samples/sample3/var.flt_removed.vcf --vcfRefName lambda_virus.fasta --verbose 1 --minConsFreq 0.6 --minConsDpth 3 --vcfFileName consensus.vcf --vcfFileName consensus_preserved.vcf snp_test/testLambdaVirus/samples/sample3/reads.all.pileup
Working Directory : /data
Hostname : login
RAM : 257243 MB
Python Version : 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
Program Version : cfsan_snp_pipeline call_consensus 2.1.0

On the note of CFSAN installation, I had it installed directly also, but the pipeline was not working due to dependencies - which is why I am using staphb.
I decided to run the whole pipeline again from scratch and see what happens (it was ran about 6 times with various errors popping up, so maybe some files got corrupted along the way). I will send a message if that solves the problem. I will also look into how I can force the pipeline to run with python 3.

Dagmara

**Comment by DagmaraNiedziela** [comment]
This is very possible. In the meantime, if I figure anything out I will also keep you posted! 

Thank you
Dagmara

**Comment by DagmaraNiedziela** [comment]
Hi Hugh, 

I reran the CFSAN pipeline with the -f option and it worked! I am not sure what the error was, but I suppose I don't need a solution... Probably a corrupted file somewhere in the middle. Sorry for the trouble! 

Dagmara

**Comment by hughrandFDA** [comment]
Strange. Thanks for letting me know. I’ll let the person here (Vishal) who has been digging around to see if he could find a cause.
H

From: DagmaraNiedziela ***@***.***>
Sent: Monday, June 14, 2021 7:40 AM
To: CFSAN-Biostatistics/snp-pipeline ***@***.***>
Cc: Rand, Hugh ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [CFSAN-Biostatistics/snp-pipeline] Error in CFSAN call_consensus: ValueError exception in function __iter__ at line 425 in file /usr/local/lib/python2.7/dist-packages/snppipeline/pileup.py (#21)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi Hugh,

I reran the CFSAN pipeline with the -f option and it worked! I am not sure what the error was, but I suppose I don't need a solution... Probably a corrupted file somewhere in the middle. Sorry for the trouble!

Dagmara
